version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: daphne -p 8000 senior.asgi:application
    volumes:
      - ./senior:/senior
      - static:/static
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.dev


  db:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  static:
  postgres_data: