version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev.db

volumes:
  static: