version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./senior:/senior
      - static:/static
    ports:
      - "80:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev


  db:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static:
  postgres_data: