# Generated by Django 4.2.3 on 2024-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togyzkumalak', '0003_bot_gamesession_game_ended_gamesession_game_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bot_images/'),
        ),
    ]
